apiVersion: apps/v1
kind: Deployment
metadata:
  name: profanity-filter-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: profanity-filter
  template:
    metadata:
      labels:
        app: profanity-filter
    spec:
      containers:
        - name: profanity-filter
          image: micknice/profanity-filter-microservice:v1
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata: 
  name: profanity-filter-service
spec: 
  selector:
    app: profanity-filter
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30000